language: java

jdk:
  - oraclejdk8

env:
  global:
    - secure: "UYVpJZqZNwXFzwY9v6e6QlgLeM7PRFjbX7NK1fXMmdD5KmF5ndSoF5zFBKnSrLU6DJ3T+l6lQ9MJ2j7BxlOraDUFPk9oiY4q1/6PUlFMtVgrW9Qj/ogeqd/qe+Cmoj7dn/wDgvt6H+13dHVtRQjyb8EM0u6d/kS0rFkpmmUgbJFoxw837NCahTU3jvIHRdJy/po/kLjf0d9/rblGc2FszALC0W80gXcdZ7Nq4ZWXRjpZnLyGOPdoqQyPQkfWm3QURGwqxGcpr3rCnLrH/LUHuGU6IDh5xdDwVmSuUYduv7jRZLArb1JvTfgIcoyo4ieMM2FUlEEdGIxRxNWx66qwEDN+jGfVaHqnRxAySNy14YuU/87Z4k5jPAerslsbiTyPIt12Fr8KOW31EPC/YVz7MK6ar8K/dwxRMtAtKFDOz26clx2I5nodU7871LdFIM8ixEiqlqY9oeA4vWK+7aB10FXrph4ieVZJ0tJ1kv+z4syk7H29fNeCY7TAsHd0PfbdVxkD2jH87rFl8yNzL6nyLsOZE1sRNLCJ2l5JSe3j3+PbEepCqKQtkTwT0pCm21GlYKCbQ7PwYGHC61sGYbszhS238tMRBtIwJYkVmXiCtwb/38R87bYxfcQtFlj3TGSRIgHyuyRLaAssUP0XKuDTm8pyDL+f3CDLt3rx3G2U+M8="
    - secure: "MuznleW/XLL2RnA3uBxIZbvVL33DIRdQ5cPN6yNKZNhSLLJAR8kFg3Dd+YR3Uk2iId0VSli00mNRvEUlyK1CwLm2Ms0zhSdAVWyJW0q7RI9XbW1wlYOfjtrYqxK/NFZlzD/iJog0aonuUQO+PqVAYf7THPNwdlrGbgNo2eQHwk/I6sINfztmTkW+Vo9bKAmtor/OqeqeylIagWeukSkN8uICm/wRVsbkY7TfM8JB8FXrGyt1FtbTLig33RDhAxwihibtQHEYUcQJSYbHX5zhbiRpFTf9ZFF3xVRdO4H6+SZWfeyMGQgzvxEkvQDIX+9L2WPK5wZDikYKukntw/l0npFERwmj9sKRTrsOz++PNsG//7vKcIjoeW/gYHG0QgHn4FQbpjU4jBQeOX/t5Nkuw/m58e5IYgfzQjuVkyRJOLnizfDB+n0Y8Jd6bZSm7w0shlpVSuhoOgciVllcLznH4In9MfYvzaknLXXGMqRFik2pAPddro5RJ2qdBf70MbxE2Oqr+UTZe0EVK5nXTQ6Iq0UDe1Q8tva2x74u/nZrOt0Jn/jr0eV/jvaSQlIEIW89vrUlDh1zazdxYpe5f+BMLAGJvf0CG19iidUPhewewe0G2sEKfp0NeZhYZOp0pA0wrqaO83CsyoyRNflr5dS7ggjqcGvnYck6WT3KtrTeXpo="
  matrix:
    - SQ_VERSION=LTS
    - SQ_VERSION=LATEST_RELEASE

cache:
  directories:
    - '$HOME/.m2/repository'

script: ./travis.sh
